### ISSUE TITLE
More than enough UTXO used for user's transaction.

### ISSUE THREAD

**Issue by charkala** [MicroBitcoinOrg/MobileWallet#1]
A MobileWallet user reported a transaction whereby the number of UTXO used was way more than needed for the transaction.

The user seems to have wanted to send just `101,000 MBC` to `Bkf51YimayheS4rbJ2tcMi8wjyMwnAJQxs` but from looking at the total inputs, there are more than needed.

TXID: [ad8edadb072487b6a21672c56dfbf64d84517cc5853a132a04fdd806b7f974af](https://microbitcoinorg.github.io/explorer/#/tx/ad8edadb072487b6a21672c56dfbf64d84517cc5853a132a04fdd806b7f974af)

What's the reason for the wallet to create more inputs for this transaction?

**Comment by itwysgsl** [comment]
Fixed https://github.com/MicroBitcoinOrg/MobileWallet/commit/fe5802171de9ed607b816d0a00541ad41982ed95
